Alternative subject as header
Altinn/altinn-events pull request #304
Opened 2023-03-06 12:13 UTC by acn-sbuad

## Description

- Alternative subject as header
- Source no longer a list, required string.
- Next link composes subject query param if only alternativeSubject header provided

## Related Issue(s)
- #108

## Verification
- [ ] **Your** code builds clean without any errors or warnings
- [ ] Manual testing done (required)
- [ ] Relevant automated test added (if you find this hard, leave it and we'll help out)
- [ ] All tests run green

## Documentation
- [ ] User documentation is updated with a separate linked PR in [altinn-studio-docs.](https://github.com/Altinn/altinn-studio-docs) (if applicable)

2023-03-10 10:17 UTC, SandGrainOne requested changes
Source must be included as a parameter in calls to db. (app events)

2023-03-10 10:17 UTC, SandGrainOne commented on test/Altinn.Platform.Events.Tests/TestingServices/EventsServiceTest.cs
> +            List<CloudEvent> actual = await eventsService.GetEvents("1", "https://ttd.apps.at22.altinn.cloud/ttd/app-test/", null, null, new List<string>() { }, 50);
Unnecessary empty braces.

2023-03-10 13:26 UTC, acn-sbuad commented on test/Altinn.Platform.Events.Tests/TestingControllers/EventsControllerTests.cs
> +                Assert.Equal(expectedCount, actual.Count);
Yeah. probably. The way I see it getting a heads up that we return a different number of events might be a help after adjusting testdata or a tip on where to start the search if the final assert doesn't match due to an unexpected next header.

2023-03-13 09:37 UTC, SandGrainOne approved these changes

2023-03-13 11:48 UTC, merged